/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package by.avramova.airline.XMLParser;

/**
 *
 * @author tot
 */
public enum PlaneFieldsEnum {
    AIRBAGMOTORPOWER, AIRBAGMOTORNAME, SEATSNUMBER, CARGOCAPACITY, FLYINGDISTANCE, FUELEXPENDITURE, 
    CRUISINGSPEED, BORTNUMBER, SEAWORTHINESS, MAXWAVEHEIGHT, SKILENGTH, SKIWIDTH,
    ROOT, BASE, MAINWHEEELDIAMETER, BACKWHEEELDIAMETER, BOBBERSNUMBER, PLANELIST, 
    AIRPLANE, HYDROPLANE, BOBBEREDPLANE, SKIEDPLANE, WHEELEDPLANE;
}
